server:
  port: 0

spring:
  application:
    name: coupon-kafka-service

  datasource:
    url: jdbc:mysql://chunsun-db:3306/coupon?serverTimezone=UTC&characterEncoding=UTF-8

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  kafka:
    consumer:
      bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092
      group-id: coupon-issue
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      max-poll-records: 1000
      enable-auto-commit: false
      properties:
        isolation.level: read_committed

    listener:
      type: batch
      poll-timeout: 100
      ack-mode: manual_immediate
      concurrency: 3