server:
  port: 0

spring:
  application:
    name: coupon-service

  datasource:
    url: jdbc:mysql://chunsun-db:3306/coupon?serverTimezone=UTC&characterEncoding=UTF-8

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  data:
    redis:
      host: coupon-redis
      port: 6379

  kafka:
    producer:
      bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 5
        batch.size: 32768
        enable.idempotence: true
        transactional.id: "coupon-tx-producer"