server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<segment>/.*)?, /$\{segment}

        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
          filters:
            - RewritePath=/member-service/(?<segment>/.*)?, /$\{segment}

        - id: coupon-service
          uri: lb://COUPON-SERVICE
          predicates:
            - Path=/coupon-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/coupon-service/(?<segment>.*), /$\{segment}

        - id: coupon-kafka-service
          uri: lb://COUPON-KAFKA-SERVICE
          predicates:
            - Path=/coupon-kafka-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/coupon-kafka-service/(?<segment>.*), /$\{segment}

        - id: rank-service
          uri: lb://RANK-SERVICE
          predicates:
            - Path=/rank-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/rank-service/(?<segment>/.*)?, /$\{segment}

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/payment-service/(?<segment>/.*)?, /$\{segment}

        - id: class-service
          uri: lb://CLASS-SERVICE
          predicates:
            - Path=/class-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/class-service/(?<segment>/.*)?, /$\{segment}

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>/.*)?, /$\{segment}