server:
  port: 0

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: kafka1:9092, kafka2:9092, kafka3:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        max.poll.records: 30
        retry.backoff.ms: 1000
        fetch.max.wait.ms: 5000
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      delivery.timeout.ms: 3000
      acks: all
      properties:
        spring.json.add.type.headers: false
    listener:
      ack-mode: manual_immediate

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.data.mongodb: DEBUG
    com.chunsun.notificationservice: DEBUG

mongodb:
  notification:
    expire: 2592000

sse:
  subscribe:
    timeout: 3600000

