spring:
  application:
    name: member-service

  datasource:
    url: jdbc:mysql://chunsun-db:3306/mydatabase
    username: chunsun
    password: chunsun
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 추가

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true  # SQL 로그 출력 (디버깅용, 운영에서는 비활성화)

server:
  port: 8082
