#server:
#  port: 0
#
#spring:
#  application:
#    name: rank-service

server:
  port: 8084

spring:
  application:
    name: rank-service
  datasource:
#    url: jdbc:mysql://chunsun-db:3306/rank
    url: jdbc:mysql://localhost:3306/rank
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always  # 애플리케이션 시작 시 SQL 스크립트 실행 가능

  hikari:
    maximum-pool-size: 10  # 커넥션 풀 크기 설정
  redis:
    host: localhost
    port: 6379
    timeout: 6000ms
    lettuce:
      max-active: 10
      max-idle: 5
      min-idle: 2
      max-wait: 5000ms


#
#  cloud:
#    config:
#      uri: http://127.0.0.1:8888
#
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
##    username: '{cipher}ac0d4fda7d75b7332ec46bdbc84c93ce47980011cf86d88e7e160b61b6a5d1c0'
##    password: '{cipher}ac0d4fda7d75b7332ec46bdbc84c93ce47980011cf86d88e7e160b61b6a5d1c0'
##    username: '{cipher}d79ddeb52eabe7f2a656753d8e65089861e6f273afb8aa2577aa08082cc0a118'
##    password: '{cipher}51552a12ded68918d03a41fecbf3afeeb213926916dc77125b08378a21a66d8e4ba5c9bf2d84603a7e08cc8f2061e91e'
#
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.orm.jdbc.bind: TRACE
#
#
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh, health, beans, busrefresh
#
#token:
#  expiration_time: 86400000
#  secret: user_token_test_123456789_test_0123456789_test_token

# ranking 가중치
ranking:
  weight:
    viewScore: 20
    classScore: 50
