server:
  port: 0

spring:
  application:
    name: auth-service
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://config-service:8888
  datasource:
    url: jdbc:mysql://chunsun-db:3306/member
    username: chunsun
    password: chunsun
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 2fe64602abc1d89964ca3c7c83cf840c
            client-secret: puvc6vnidXq1Rq6NvIYOZtIafcymsTRc
            redirect-uri: "http://i12a505.p.ssafy.io/auth-service/login" ## 이후 프론트 인가 코드 리다이렉트 URL로 변경
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  data:
    redis:
      host: auth-redis-db
      port: 6379

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

#    username: '{cipher}ac0d4fda7d75b7332ec46bdbc84c93ce47980011cf86d88e7e160b61b6a5d1c0'
#    password: '{cipher}ac0d4fda7d75b7332ec46bdbc84c93ce47980011cf86d88e7e160b61b6a5d1c0'
#    username: '{cipher}d79ddeb52eabe7f2a656753d8e65089861e6f273afb8aa2577aa08082cc0a118'
#    password: '{cipher}51552a12ded68918d03a41fecbf3afeeb213926916dc77125b08378a21a66d8e4ba5c9bf2d84603a7e08cc8f2061e91e'

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

token:
  access_expiration_time: 3600000
  refresh_expiration_time: 2592000000
  secret: user_token_test_123456789_test_0123456789_test_token

snowflake:
  machine-id: 1